version: '3'

services:
    api:
        container_name: api-base
        build:
            context: .
        image: img-api-base
        restart: unless-stopped
        environment:
            PORT: 4000
            API_NAME: "EloMoney API"
            API_DESCR: "Api for EloMoney services"
            API_TOKEN_AUTH_SCHEME: JWT
            API_ACCESS_TOKEN_SECRET: 4cc3SS70k3n$eCr37|3L0moN3Y4P1@2021
            API_ACCESS_TOKEN_EXPIRES_IN: 5m
            API_REFRESH_TOKEN_SECRET: r3FRe$h70k3n$eCr37|3L0moN3Y4P1@2021
            API_REFRESH_TOKEN_EXPIRES_IN: 1h
            API_ROOT_ACCOUNT_EMAIL: stein.bbs@gmail.com
            API_ROOT_ACCOUNT_USER: stein.bbs@gmail.com
            API_ROOT_ACCOUNT_PASS: 123mud@r
            MONGODB_URI: mongodb://root:toor@db:27017/elomoney_api?authSource=admin
        ports:
            - 5000:4000
        depends_on:
            - db

    db:
        image: mongo:4.1.8-xenial
        container_name: db
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=toor
        volumes:
            - dbdata:/data/db

volumes:
  dbdata:
