version: '3'

services:
    api:
        container_name: api-base
        build:
            context: .
        image: img-api-base
        restart: unless-stopped
        env_file: ./src/.env
        volumes:
            - ./src:/api_base
            - /api_base/node_modules
        ports:
            - 4000:4000
        depends_on:
            - db

    db:
        image: mongo:4.1.8-xenial
        container_name: api-base-db
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=your_mongodb_username
            - MONGO_INITDB_ROOT_PASSWORD=your_mongodb_password
        volumes:
            - dbdata:/data/db

volumes:
  dbdata:
