version: '3'

services:
    api:
        container_name: rest-api-base
        build:
            context: .
        image: img-rest-api-base
        restart: unless-stopped
        env_file: ./.env
        volumes:
            - ./src:/rest_api_base
            - /rest_api_base/node_modules
            - ./data/log:/rest_api_base/log
        ports:
            - 4000:4000
        depends_on:
            - db

    db:
        image: mongo:4.1.8-xenial
        container_name: rest-api-base-db
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=toor
        volumes:
            - ./data/db:/data/db

    cache:
        container_name: rest-api-base-cache
        image: redis
        command: ["redis-server", "--appendonly", "yes"]
        ports:
            - 7001:6379
        volumes:
            - ./data/cache:/data
        restart: unless-stopped

volumes:
  data:
